"""Vertex AI / Jupyter notebook generator."""

from __future__ import annotations

import json


def _code_cell(source: str | list[str]) -> dict:
    """Create a Jupyter code cell."""
    if isinstance(source, str):
        source = source.split("\n")
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source],
    }


def _markdown_cell(source: str | list[str]) -> dict:
    """Create a Jupyter markdown cell."""
    if isinstance(source, str):
        source = source.split("\n")
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in source],
    }


NOTEBOOK_TEMPLATES: dict[str, dict] = {}


def _churn_prediction_notebook(project_id: str, dataset: str) -> dict:
    cells = [
        _markdown_cell([
            "# Churn Prediction Model",
            "",
            "Telco subscriber churn prediction using BigQuery ML.",
            "Generated by TAA (Telco Analytics Accelerator).",
            "",
            "**Approach**: Logistic regression baseline + XGBoost comparison using",
            "CDR usage patterns, billing history, and subscriber profile features.",
        ]),
        _code_cell([
            "# Setup",
            "from google.cloud import bigquery",
            "",
            f'PROJECT_ID = "{project_id}"',
            f'DATASET = "{dataset}"',
            "client = bigquery.Client(project=PROJECT_ID)",
        ]),
        _markdown_cell("## 1. Feature Engineering"),
        _code_cell([
            "feature_query = f\"\"\"",
            "CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET}.churn_features` AS",
            "SELECT",
            "    s.subscriber_id,",
            "    s.segment,",
            "    s.account_type,",
            "    DATE_DIFF(CURRENT_DATE(), s.activation_date, DAY) AS tenure_days,",
            "    COALESCE(cdr.total_calls_30d, 0) AS total_calls_30d,",
            "    COALESCE(cdr.total_data_mb_30d, 0) AS total_data_mb_30d,",
            "    COALESCE(cdr.avg_call_duration_30d, 0) AS avg_call_duration_30d,",
            "    COALESCE(inv.avg_monthly_charge, 0) AS avg_monthly_charge,",
            "    COALESCE(inv.payment_failures_90d, 0) AS payment_failures_90d,",
            "    IF(s.status = 'terminated' AND s.deactivation_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY), 1, 0) AS churned",
            "FROM `{PROJECT_ID}.subscriber_ds.subscriber_profile` s",
            "LEFT JOIN (",
            "    SELECT subscriber_id,",
            "        COUNT(*) AS total_calls_30d,",
            "        SUM(bytes_downlink + bytes_uplink) / 1048576 AS total_data_mb_30d,",
            "        AVG(duration_seconds) AS avg_call_duration_30d",
            "    FROM `{PROJECT_ID}.cdr_event_ds.voice_cdr`",
            "    WHERE event_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)",
            "    GROUP BY subscriber_id",
            ") cdr ON s.subscriber_id = cdr.subscriber_id",
            "LEFT JOIN (",
            "    SELECT account_id,",
            "        AVG(net_amount) AS avg_monthly_charge,",
            "        COUNTIF(payment_status = 'failed') AS payment_failures_90d",
            "    FROM `{PROJECT_ID}.revenue_invoice_ds.invoice`",
            "    WHERE bill_cycle_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)",
            "    GROUP BY account_id",
            ") inv ON s.account_id = inv.account_id",
            '\"\"\"',
            "",
            "client.query(feature_query).result()",
            'print("Feature table created.")',
        ]),
        _markdown_cell("## 2. Train Logistic Regression Baseline"),
        _code_cell([
            "lr_query = f\"\"\"",
            "CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET}.churn_logistic`",
            "OPTIONS(",
            "    model_type='LOGISTIC_REG',",
            "    input_label_cols=['churned'],",
            "    auto_class_weights=TRUE,",
            "    max_iterations=20",
            ") AS",
            "SELECT * EXCEPT(subscriber_id)",
            "FROM `{PROJECT_ID}.{DATASET}.churn_features`",
            "WHERE tenure_days > 30",
            '\"\"\"',
            "",
            "client.query(lr_query).result()",
            'print("Logistic regression model trained.")',
        ]),
        _markdown_cell("## 3. Train XGBoost Comparison"),
        _code_cell([
            "xgb_query = f\"\"\"",
            "CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET}.churn_xgboost`",
            "OPTIONS(",
            "    model_type='BOOSTED_TREE_CLASSIFIER',",
            "    input_label_cols=['churned'],",
            "    auto_class_weights=TRUE,",
            "    num_parallel_tree=5,",
            "    max_iterations=50",
            ") AS",
            "SELECT * EXCEPT(subscriber_id)",
            "FROM `{PROJECT_ID}.{DATASET}.churn_features`",
            "WHERE tenure_days > 30",
            '\"\"\"',
            "",
            "client.query(xgb_query).result()",
            'print("XGBoost model trained.")',
        ]),
        _markdown_cell("## 4. Evaluate Models"),
        _code_cell([
            "eval_query = f\"\"\"",
            "SELECT 'logistic' AS model,",
            "    precision, recall, accuracy, f1_score, roc_auc",
            "FROM ML.EVALUATE(MODEL `{PROJECT_ID}.{DATASET}.churn_logistic`)",
            "UNION ALL",
            "SELECT 'xgboost' AS model,",
            "    precision, recall, accuracy, f1_score, roc_auc",
            "FROM ML.EVALUATE(MODEL `{PROJECT_ID}.{DATASET}.churn_xgboost`)",
            '\"\"\"',
            "",
            "results = client.query(eval_query).to_dataframe()",
            "display(results)",
        ]),
        _markdown_cell("## 5. Score Active Subscribers"),
        _code_cell([
            "predict_query = f\"\"\"",
            "SELECT subscriber_id,",
            "    predicted_churned AS churn_prediction,",
            "    predicted_churned_probs[OFFSET(1)].prob AS churn_probability",
            "FROM ML.PREDICT(",
            "    MODEL `{PROJECT_ID}.{DATASET}.churn_xgboost`,",
            "    (SELECT * FROM `{PROJECT_ID}.{DATASET}.churn_features` WHERE churned = 0)",
            ")",
            "ORDER BY churn_probability DESC",
            "LIMIT 1000",
            '\"\"\"',
            "",
            "at_risk = client.query(predict_query).to_dataframe()",
            'print(f"Top {len(at_risk)} at-risk subscribers identified.")',
            "display(at_risk.head(20))",
        ]),
    ]
    return _notebook(cells)


def _revenue_leakage_notebook(project_id: str, dataset: str) -> dict:
    cells = [
        _markdown_cell([
            "# Revenue Leakage Detection",
            "",
            "Anomaly detection on rated CDR amounts using BigQuery ML unsupervised clustering.",
            "Generated by TAA (Telco Analytics Accelerator).",
        ]),
        _code_cell([
            "from google.cloud import bigquery",
            "",
            f'PROJECT_ID = "{project_id}"',
            f'DATASET = "{dataset}"',
            "client = bigquery.Client(project=PROJECT_ID)",
        ]),
        _markdown_cell("## 1. Build Leakage Feature Table"),
        _code_cell([
            "feature_query = f\"\"\"",
            "CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET}.leakage_features` AS",
            "SELECT",
            "    cdr.cdr_id,",
            "    cdr.subscriber_id,",
            "    cdr.call_type,",
            "    cdr.duration_seconds,",
            "    cdr.charge_amount,",
            "    cdr.rated_amount,",
            "    ABS(cdr.charge_amount - cdr.rated_amount) AS charge_delta,",
            "    CASE WHEN cdr.charge_amount = 0 AND cdr.duration_seconds > 0 THEN 1 ELSE 0 END AS zero_charge_flag,",
            "    rp.monthly_fee AS plan_fee,",
            "    SAFE_DIVIDE(cdr.charge_amount, rp.monthly_fee) AS charge_to_plan_ratio",
            "FROM `{PROJECT_ID}.cdr_event_ds.voice_cdr` cdr",
            "LEFT JOIN `{PROJECT_ID}.subscriber_ds.subscriber_profile` s ON cdr.subscriber_id = s.subscriber_id",
            "LEFT JOIN `{PROJECT_ID}.product_catalogue_ds.rate_plan` rp ON s.rate_plan_id = rp.plan_id",
            "WHERE cdr.event_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)",
            '\"\"\"',
            "",
            "client.query(feature_query).result()",
            'print("Leakage feature table created.")',
        ]),
        _markdown_cell("## 2. Anomaly Detection (K-Means Clustering)"),
        _code_cell([
            "cluster_query = f\"\"\"",
            "CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET}.leakage_clusters`",
            "OPTIONS(",
            "    model_type='KMEANS',",
            "    num_clusters=5,",
            "    standardize_features=TRUE",
            ") AS",
            "SELECT charge_delta, zero_charge_flag, charge_to_plan_ratio, duration_seconds",
            "FROM `{PROJECT_ID}.{DATASET}.leakage_features`",
            "WHERE charge_delta IS NOT NULL",
            '\"\"\"',
            "",
            "client.query(cluster_query).result()",
            'print("K-Means model trained.")',
        ]),
        _markdown_cell("## 3. Identify Anomalous Clusters"),
        _code_cell([
            "anomaly_query = f\"\"\"",
            "SELECT",
            "    CENTROID_ID AS cluster_id,",
            "    COUNT(*) AS record_count,",
            "    AVG(charge_delta) AS avg_charge_delta,",
            "    SUM(charge_delta) AS total_leakage_estimate,",
            "    AVG(zero_charge_flag) AS zero_charge_rate",
            "FROM ML.PREDICT(",
            "    MODEL `{PROJECT_ID}.{DATASET}.leakage_clusters`,",
            "    (SELECT * FROM `{PROJECT_ID}.{DATASET}.leakage_features`)",
            ")",
            "GROUP BY CENTROID_ID",
            "ORDER BY avg_charge_delta DESC",
            '\"\"\"',
            "",
            "clusters = client.query(anomaly_query).to_dataframe()",
            "display(clusters)",
        ]),
        _markdown_cell("## 4. Extract Leakage CDRs"),
        _code_cell([
            "leakage_query = f\"\"\"",
            "SELECT f.cdr_id, f.subscriber_id, f.call_type,",
            "    f.duration_seconds, f.charge_amount, f.rated_amount,",
            "    f.charge_delta, p.CENTROID_ID AS anomaly_cluster",
            "FROM ML.PREDICT(",
            "    MODEL `{PROJECT_ID}.{DATASET}.leakage_clusters`,",
            "    (SELECT * FROM `{PROJECT_ID}.{DATASET}.leakage_features`)",
            ") p",
            "JOIN `{PROJECT_ID}.{DATASET}.leakage_features` f USING(cdr_id)",
            "WHERE p.CENTROID_ID IN (",
            "    SELECT CENTROID_ID FROM (",
            "        SELECT CENTROID_ID, AVG(charge_delta) AS avg_delta",
            "        FROM ML.PREDICT(MODEL `{PROJECT_ID}.{DATASET}.leakage_clusters`,",
            "            (SELECT * FROM `{PROJECT_ID}.{DATASET}.leakage_features`))",
            "        GROUP BY CENTROID_ID ORDER BY avg_delta DESC LIMIT 2",
            "    )",
            ")",
            "ORDER BY charge_delta DESC",
            "LIMIT 500",
            '\"\"\"',
            "",
            "leakage_cdrs = client.query(leakage_query).to_dataframe()",
            'print(f"Identified {len(leakage_cdrs)} potentially leaked CDRs")',
            'print(f"Estimated total leakage: ${leakage_cdrs.charge_delta.sum():,.2f}")',
            "display(leakage_cdrs.head(20))",
        ]),
    ]
    return _notebook(cells)


def _subscriber_ltv_notebook(project_id: str, dataset: str) -> dict:
    cells = [
        _markdown_cell([
            "# Subscriber Lifetime Value (LTV) Prediction",
            "",
            "LTV prediction using billing history, plan tenure, and usage signals.",
            "Generated by TAA (Telco Analytics Accelerator).",
        ]),
        _code_cell([
            "from google.cloud import bigquery",
            "",
            f'PROJECT_ID = "{project_id}"',
            f'DATASET = "{dataset}"',
            "client = bigquery.Client(project=PROJECT_ID)",
        ]),
        _markdown_cell("## 1. Build LTV Features"),
        _code_cell([
            "feature_query = f\"\"\"",
            "CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET}.ltv_features` AS",
            "SELECT",
            "    s.subscriber_id,",
            "    s.segment,",
            "    DATE_DIFF(COALESCE(s.deactivation_date, CURRENT_DATE()), s.activation_date, MONTH) AS tenure_months,",
            "    COALESCE(inv.total_revenue, 0) AS total_revenue,",
            "    COALESCE(inv.avg_monthly_revenue, 0) AS avg_monthly_revenue,",
            "    COALESCE(inv.months_active, 1) AS months_active,",
            "    COALESCE(cdr.total_sessions, 0) AS total_sessions,",
            "    COALESCE(cdr.total_data_gb, 0) AS total_data_gb,",
            "    COALESCE(inv.total_revenue, 0) / GREATEST(DATE_DIFF(COALESCE(s.deactivation_date, CURRENT_DATE()), s.activation_date, MONTH), 1) AS arpu,",
            "    IF(s.status = 'terminated', 1, 0) AS is_churned",
            "FROM `{PROJECT_ID}.subscriber_ds.subscriber_profile` s",
            "LEFT JOIN (",
            "    SELECT account_id,",
            "        SUM(net_amount) AS total_revenue,",
            "        AVG(net_amount) AS avg_monthly_revenue,",
            "        COUNT(DISTINCT bill_cycle_date) AS months_active",
            "    FROM `{PROJECT_ID}.revenue_invoice_ds.invoice`",
            "    GROUP BY account_id",
            ") inv ON s.account_id = inv.account_id",
            "LEFT JOIN (",
            "    SELECT subscriber_id,",
            "        COUNT(*) AS total_sessions,",
            "        SUM(bytes_downlink + bytes_uplink) / 1073741824 AS total_data_gb",
            "    FROM `{PROJECT_ID}.cdr_event_ds.data_cdr`",
            "    GROUP BY subscriber_id",
            ") cdr ON s.subscriber_id = cdr.subscriber_id",
            '\"\"\"',
            "",
            "client.query(feature_query).result()",
            'print("LTV feature table created.")',
        ]),
        _markdown_cell("## 2. Train LTV Model (Linear Regression)"),
        _code_cell([
            "train_query = f\"\"\"",
            "CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET}.ltv_model`",
            "OPTIONS(",
            "    model_type='LINEAR_REG',",
            "    input_label_cols=['total_revenue'],",
            "    max_iterations=20,",
            "    l2_reg=0.1",
            ") AS",
            "SELECT",
            "    tenure_months, avg_monthly_revenue, months_active,",
            "    total_sessions, total_data_gb, arpu, is_churned,",
            "    total_revenue",
            "FROM `{PROJECT_ID}.{DATASET}.ltv_features`",
            "WHERE tenure_months >= 3",
            '\"\"\"',
            "",
            "client.query(train_query).result()",
            'print("LTV model trained.")',
        ]),
        _markdown_cell("## 3. Evaluate"),
        _code_cell([
            "eval_query = f\"\"\"",
            "SELECT * FROM ML.EVALUATE(MODEL `{PROJECT_ID}.{DATASET}.ltv_model`)",
            '\"\"\"',
            "",
            "eval_results = client.query(eval_query).to_dataframe()",
            "display(eval_results)",
        ]),
        _markdown_cell("## 4. Predict LTV for Active Subscribers"),
        _code_cell([
            "predict_query = f\"\"\"",
            "SELECT subscriber_id, segment,",
            "    ROUND(predicted_total_revenue, 2) AS predicted_ltv,",
            "    tenure_months, arpu",
            "FROM ML.PREDICT(",
            "    MODEL `{PROJECT_ID}.{DATASET}.ltv_model`,",
            "    (SELECT * FROM `{PROJECT_ID}.{DATASET}.ltv_features` WHERE is_churned = 0)",
            ")",
            "ORDER BY predicted_total_revenue DESC",
            "LIMIT 1000",
            '\"\"\"',
            "",
            "ltv_predictions = client.query(predict_query).to_dataframe()",
            'print(f"Predicted LTV for {len(ltv_predictions)} active subscribers")',
            "display(ltv_predictions.describe())",
            "display(ltv_predictions.head(20))",
        ]),
    ]
    return _notebook(cells)


def _notebook(cells: list[dict]) -> dict:
    """Wrap cells into a valid .ipynb structure."""
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "cells": cells,
    }


NOTEBOOK_TEMPLATES = {
    "churn_prediction": _churn_prediction_notebook,
    "revenue_leakage": _revenue_leakage_notebook,
    "subscriber_ltv": _subscriber_ltv_notebook,
}


class NotebookGenerator:
    """Generates Vertex AI / Jupyter notebook (.ipynb) files."""

    def __init__(self, project_id: str = "telco-analytics") -> None:
        self._project_id = project_id

    def generate(self, template_name: str, dataset_name: str = "analytics_ds") -> str:
        """Generate a single notebook as a JSON string."""
        builder = NOTEBOOK_TEMPLATES.get(template_name)
        if builder is None:
            raise ValueError(
                f"Unknown notebook template: {template_name}. "
                f"Available: {list(NOTEBOOK_TEMPLATES.keys())}"
            )
        nb = builder(self._project_id, dataset_name)
        return json.dumps(nb, indent=1)

    def generate_all(self, dataset_name: str = "analytics_ds") -> dict[str, str]:
        """Generate all notebooks. Returns {filename: json_content}."""
        results = {}
        for name in NOTEBOOK_TEMPLATES:
            results[f"{name}.ipynb"] = self.generate(name, dataset_name)
        return results

    def list_templates(self) -> list[str]:
        return list(NOTEBOOK_TEMPLATES.keys())
