--- churn_prediction ---
-- =============================================================================
-- Churn Prediction Feature Engineering Pipeline
-- Generated by TAA (Telco Analytics Accelerator)
-- Target: BigQuery ML / Vertex AI
-- =============================================================================

-- Step 1: Create churn feature table
CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.churn_features` AS
WITH subscriber_base AS (
  SELECT
    sp.subscriber_id,
    sp.msisdn,
    sp.activation_date,
    sp.status,
    sp.subscriber_type,
    sp.subscriber_segment,
    sp.lifecycle_stage,
    DATE_DIFF(CURRENT_DATE(), sp.activation_date, DAY) AS tenure_days,
    DATE_DIFF(CURRENT_DATE(), sp.last_activity_date, DAY) AS days_since_last_activity,
    sp.churn_risk_score AS previous_churn_score
  FROM `telco-analytics.subscriber_ds.subscriber_profile` sp
  WHERE sp.status IN ('active', 'suspended')
),

usage_30d AS (
  SELECT
    subscriber_id,
    AVG(data_usage_mb) AS avg_daily_data_mb_30d,
    AVG(voice_minutes_mo) AS avg_daily_voice_min_30d,
    SUM(data_usage_mb) AS total_data_mb_30d,
    SUM(voice_minutes_mo + voice_minutes_mt) AS total_voice_min_30d,
    SUM(sms_count_mo) AS total_sms_30d,
    COUNT(DISTINCT usage_date) AS active_days_30d,
    AVG(session_count) AS avg_sessions_30d
  FROM `telco-analytics.usage_analytics_ds.usage_summary`
  WHERE usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
    AND usage_period = 'daily'
  GROUP BY subscriber_id
),

usage_trend AS (
  SELECT
    subscriber_id,
    -- Compare last 30 days vs previous 30 days
    SAFE_DIVIDE(
      SUM(CASE WHEN usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY) THEN data_usage_mb END),
      NULLIF(SUM(CASE WHEN usage_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 31 DAY) THEN data_usage_mb END), 0)
    ) AS data_usage_trend_ratio,
    SAFE_DIVIDE(
      SUM(CASE WHEN usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY) THEN voice_minutes_mo END),
      NULLIF(SUM(CASE WHEN usage_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 31 DAY) THEN voice_minutes_mo END), 0)
    ) AS voice_usage_trend_ratio
  FROM `telco-analytics.usage_analytics_ds.usage_summary`
  WHERE usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY)
    AND usage_period = 'daily'
  GROUP BY subscriber_id
),

revenue_90d AS (
  SELECT
    i.subscriber_id,
    SUM(i.total_amount) AS total_revenue_90d,
    AVG(i.total_amount) AS avg_monthly_revenue,
    COUNT(DISTINCT i.invoice_id) AS invoice_count_90d,
    MAX(p.payment_date) AS last_payment_date,
    AVG(DATE_DIFF(p.payment_date, i.due_date, DAY)) AS avg_payment_delay_days,
    COUNTIF(p.payment_date > i.due_date) AS late_payment_count
  FROM `telco-analytics.revenue_invoice_ds.invoice` i
  LEFT JOIN `telco-analytics.revenue_invoice_ds.payment` p ON i.invoice_id = p.invoice_id
  WHERE i.bill_cycle_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)
  GROUP BY i.subscriber_id
),

contract_info AS (
  SELECT
    subscriber_id,
    MIN(CASE WHEN status = 'active' THEN DATE_DIFF(end_date, CURRENT_DATE(), DAY) END) AS contract_remaining_days,
    MAX(CASE WHEN status = 'active' THEN auto_renew_flag END) AS auto_renew,
    COUNT(*) AS total_contracts
  FROM `telco-analytics.subscriber_ds.subscriber_contract`
  GROUP BY subscriber_id
),

device_info AS (
  SELECT
    subscriber_id,
    MAX(CASE WHEN device_status = 'active' THEN is_5g_capable END) AS has_5g_device,
    MAX(CASE WHEN device_status = 'active' THEN device_type END) AS primary_device_type,
    DATE_DIFF(CURRENT_DATE(), MIN(activation_date), MONTH) AS device_age_months
  FROM `telco-analytics.subscriber_ds.subscriber_device`
  GROUP BY subscriber_id
),

network_quality AS (
  SELECT
    v.subscriber_id,
    AVG(CASE WHEN v.event_type IN ('dropped_call', 'failed_call') THEN 1.0 ELSE 0.0 END) AS call_failure_rate,
    AVG(d.bytes_downloaded / NULLIF(d.session_duration_seconds, 0) * 8 / 1000000) AS avg_throughput_mbps
  FROM `telco-analytics.cdr_event_ds.voice_cdr` v
  LEFT JOIN `telco-analytics.cdr_event_ds.data_cdr` d ON v.subscriber_id = d.subscriber_id
  WHERE v.event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
  GROUP BY v.subscriber_id
)

SELECT
  sb.subscriber_id,
  sb.msisdn,
  sb.subscriber_type,
  sb.subscriber_segment,
  sb.tenure_days,
  sb.days_since_last_activity,
  COALESCE(u.avg_daily_data_mb_30d, 0) AS avg_daily_data_mb_30d,
  COALESCE(u.avg_daily_voice_min_30d, 0) AS avg_daily_voice_min_30d,
  COALESCE(u.total_data_mb_30d, 0) AS total_data_mb_30d,
  COALESCE(u.total_voice_min_30d, 0) AS total_voice_min_30d,
  COALESCE(u.active_days_30d, 0) AS active_days_30d,
  COALESCE(ut.data_usage_trend_ratio, 1.0) AS data_usage_trend_ratio,
  COALESCE(ut.voice_usage_trend_ratio, 1.0) AS voice_usage_trend_ratio,
  COALESCE(r.total_revenue_90d, 0) AS total_revenue_90d,
  COALESCE(r.avg_monthly_revenue, 0) AS avg_monthly_revenue,
  COALESCE(r.avg_payment_delay_days, 0) AS avg_payment_delay_days,
  COALESCE(r.late_payment_count, 0) AS late_payment_count,
  COALESCE(ci.contract_remaining_days, 0) AS contract_remaining_days,
  COALESCE(ci.auto_renew, FALSE) AS auto_renew,
  COALESCE(di.has_5g_device, FALSE) AS has_5g_device,
  COALESCE(di.device_age_months, 0) AS device_age_months,
  COALESCE(nq.call_failure_rate, 0) AS call_failure_rate,
  COALESCE(nq.avg_throughput_mbps, 0) AS avg_throughput_mbps,
  -- Label: subscriber churned within next 30 days (for training)
  CASE
    WHEN sb.status = 'churned' AND sb.days_since_last_activity <= 30 THEN 1
    ELSE 0
  END AS churned_label,
  CURRENT_TIMESTAMP() AS feature_computation_timestamp
FROM subscriber_base sb
LEFT JOIN usage_30d u ON sb.subscriber_id = u.subscriber_id
LEFT JOIN usage_trend ut ON sb.subscriber_id = ut.subscriber_id
LEFT JOIN revenue_90d r ON sb.subscriber_id = r.subscriber_id
LEFT JOIN contract_info ci ON sb.subscriber_id = ci.subscriber_id
LEFT JOIN device_info di ON sb.subscriber_id = di.subscriber_id
LEFT JOIN network_quality nq ON sb.subscriber_id = nq.subscriber_id;

-- Step 2: Train BigQuery ML model
CREATE OR REPLACE MODEL `telco-analytics.analytics_ds.churn_model`
OPTIONS(
  model_type='BOOSTED_TREE_CLASSIFIER',
  input_label_cols=['churned_label'],
  max_iterations=50,
  learn_rate=0.1,
  early_stop=TRUE,
  data_split_method='AUTO_SPLIT'
) AS
SELECT
  * EXCEPT(subscriber_id, msisdn, feature_computation_timestamp)
FROM `telco-analytics.analytics_ds.churn_features`
WHERE churned_label IS NOT NULL;

-- Step 3: Generate predictions
CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.churn_predictions` AS
SELECT
  subscriber_id,
  msisdn,
  predicted_churned_label AS predicted_churn,
  predicted_churned_label_probs[OFFSET(1)].prob AS churn_probability,
  CASE
    WHEN predicted_churned_label_probs[OFFSET(1)].prob >= 0.8 THEN 'CRITICAL'
    WHEN predicted_churned_label_probs[OFFSET(1)].prob >= 0.6 THEN 'HIGH'
    WHEN predicted_churned_label_probs[OFFSET(1)].prob >= 0.4 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS risk_category,
  CURRENT_TIMESTAMP() AS prediction_timestamp
FROM ML.PREDICT(
  MODEL `telco-analytics.analytics_ds.churn_model`,
  (SELECT * EXCEPT(churned_label, feature_computation_timestamp)
   FROM `telco-analytics.analytics_ds.churn_features`)
);
--- revenue_leakage ---
-- =============================================================================
-- Revenue Leakage Detection Queries
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

-- 1. CDR vs Invoice Reconciliation — detect unbilled usage
CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.revenue_leakage_cdr_unbilled` AS
WITH rated_cdrs AS (
  SELECT
    subscriber_id,
    DATE_TRUNC(event_date, MONTH) AS billing_month,
    SUM(rated_amount) AS total_rated_amount,
    COUNT(*) AS cdr_count,
    SUM(duration_seconds) AS total_duration_seconds
  FROM `telco-analytics.cdr_event_ds.voice_cdr`
  WHERE event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
  GROUP BY subscriber_id, billing_month
),
billed_amounts AS (
  SELECT
    subscriber_id,
    DATE_TRUNC(bill_cycle_date, MONTH) AS billing_month,
    SUM(CASE WHEN charge_type = 'usage' THEN amount ELSE 0 END) AS total_billed_usage,
    SUM(amount) AS total_billed_amount
  FROM `telco-analytics.revenue_invoice_ds.invoice` i
  JOIN `telco-analytics.revenue_invoice_ds.invoice_line_item` li ON i.invoice_id = li.invoice_id
  WHERE i.bill_cycle_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
  GROUP BY subscriber_id, billing_month
)
SELECT
  r.subscriber_id,
  r.billing_month,
  r.total_rated_amount,
  r.cdr_count,
  COALESCE(b.total_billed_usage, 0) AS total_billed_usage,
  r.total_rated_amount - COALESCE(b.total_billed_usage, 0) AS leakage_amount,
  SAFE_DIVIDE(r.total_rated_amount - COALESCE(b.total_billed_usage, 0), r.total_rated_amount) * 100 AS leakage_pct,
  CASE
    WHEN ABS(r.total_rated_amount - COALESCE(b.total_billed_usage, 0)) > 100 THEN 'CRITICAL'
    WHEN ABS(r.total_rated_amount - COALESCE(b.total_billed_usage, 0)) > 10 THEN 'HIGH'
    WHEN ABS(r.total_rated_amount - COALESCE(b.total_billed_usage, 0)) > 1 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS severity,
  CURRENT_TIMESTAMP() AS detection_timestamp
FROM rated_cdrs r
LEFT JOIN billed_amounts b ON r.subscriber_id = b.subscriber_id AND r.billing_month = b.billing_month
WHERE ABS(r.total_rated_amount - COALESCE(b.total_billed_usage, 0)) > 0.01;

-- 2. Zero-rated CDR detection — calls that should have been charged
CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.revenue_leakage_zero_rated` AS
SELECT
  subscriber_id,
  msisdn,
  event_date,
  event_type,
  duration_seconds,
  called_number,
  rated_amount,
  'Zero-rated CDR with non-zero duration' AS leakage_type,
  CURRENT_TIMESTAMP() AS detection_timestamp
FROM `telco-analytics.cdr_event_ds.voice_cdr`
WHERE rated_amount = 0
  AND duration_seconds > 0
  AND event_type NOT IN ('emergency', 'free_call', 'toll_free')
  AND event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY);

-- 3. Interconnect settlement variance
CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.revenue_leakage_interconnect` AS
WITH our_records AS (
  SELECT
    partner_operator,
    direction,
    DATE_TRUNC(event_date, MONTH) AS settlement_month,
    SUM(duration_seconds) AS our_total_seconds,
    SUM(rated_amount) AS our_total_amount,
    COUNT(*) AS our_record_count
  FROM `telco-analytics.interconnect_roaming_ds.interconnect_cdr`
  WHERE event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
  GROUP BY partner_operator, direction, settlement_month
),
partner_invoices AS (
  SELECT
    partner_operator,
    CASE WHEN direction = 'payable' THEN 'outbound' ELSE 'inbound' END AS direction,
    DATE_TRUNC(invoice_period_start, MONTH) AS settlement_month,
    SUM(total_minutes) * 60 AS partner_total_seconds,
    SUM(total_amount) AS partner_total_amount
  FROM `telco-analytics.interconnect_roaming_ds.interconnect_invoice`
  WHERE invoice_period_start >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
  GROUP BY partner_operator, direction, settlement_month
)
SELECT
  o.partner_operator,
  o.direction,
  o.settlement_month,
  o.our_total_seconds,
  COALESCE(p.partner_total_seconds, 0) AS partner_total_seconds,
  o.our_total_seconds - COALESCE(p.partner_total_seconds, 0) AS duration_variance_seconds,
  o.our_total_amount,
  COALESCE(p.partner_total_amount, 0) AS partner_total_amount,
  o.our_total_amount - COALESCE(p.partner_total_amount, 0) AS amount_variance,
  CURRENT_TIMESTAMP() AS detection_timestamp
FROM our_records o
LEFT JOIN partner_invoices p
  ON o.partner_operator = p.partner_operator
  AND o.direction = p.direction
  AND o.settlement_month = p.settlement_month
WHERE ABS(o.our_total_amount - COALESCE(p.partner_total_amount, 0)) > 100;

-- 4. Revenue leakage summary dashboard view
CREATE OR REPLACE VIEW `telco-analytics.analytics_ds.revenue_leakage_summary` AS
SELECT
  'CDR vs Invoice' AS leakage_category,
  COUNT(*) AS case_count,
  SUM(ABS(leakage_amount)) AS total_leakage_amount,
  'SAR' AS currency
FROM `telco-analytics.analytics_ds.revenue_leakage_cdr_unbilled`
WHERE severity IN ('CRITICAL', 'HIGH')
UNION ALL
SELECT
  'Zero-Rated CDRs' AS leakage_category,
  COUNT(*) AS case_count,
  COUNT(*) * 0.5 AS total_leakage_amount,  -- Estimated avg charge per CDR
  'SAR' AS currency
FROM `telco-analytics.analytics_ds.revenue_leakage_zero_rated`
UNION ALL
SELECT
  'Interconnect Variance' AS leakage_category,
  COUNT(*) AS case_count,
  SUM(ABS(amount_variance)) AS total_leakage_amount,
  'SAR' AS currency
FROM `telco-analytics.analytics_ds.revenue_leakage_interconnect`;
--- arpu_analysis ---
-- =============================================================================
-- ARPU Analysis & Segmentation
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.arpu_monthly` AS
WITH monthly_revenue AS (
  SELECT
    i.subscriber_id,
    sp.msisdn,
    sp.subscriber_type,
    sp.subscriber_segment,
    sp.lifecycle_stage,
    DATE_TRUNC(i.bill_cycle_date, MONTH) AS revenue_month,
    SUM(CASE WHEN li.charge_type = 'recurring' THEN li.amount ELSE 0 END) AS recurring_revenue,
    SUM(CASE WHEN li.charge_type = 'usage' THEN li.amount ELSE 0 END) AS usage_revenue,
    SUM(CASE WHEN li.charge_type = 'one-time' THEN li.amount ELSE 0 END) AS onetime_revenue,
    SUM(li.amount) AS total_revenue,
    SUM(COALESCE(li.discount_amount, 0)) AS total_discount
  FROM `telco-analytics.revenue_invoice_ds.invoice` i
  JOIN `telco-analytics.revenue_invoice_ds.invoice_line_item` li ON i.invoice_id = li.invoice_id
  JOIN `telco-analytics.subscriber_ds.subscriber_profile` sp ON i.subscriber_id = sp.subscriber_id
  WHERE i.bill_cycle_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH)
  GROUP BY i.subscriber_id, sp.msisdn, sp.subscriber_type, sp.subscriber_segment, sp.lifecycle_stage, revenue_month
),

usage_split AS (
  SELECT
    subscriber_id,
    DATE_TRUNC(usage_date, MONTH) AS usage_month,
    SUM(data_usage_mb) AS total_data_mb,
    SUM(voice_minutes_mo) AS total_voice_min,
    SUM(sms_count_mo) AS total_sms
  FROM `telco-analytics.usage_analytics_ds.usage_summary`
  WHERE usage_period = 'daily'
    AND usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH)
  GROUP BY subscriber_id, usage_month
)

SELECT
  mr.subscriber_id,
  mr.msisdn,
  mr.subscriber_type,
  mr.subscriber_segment,
  mr.lifecycle_stage,
  mr.revenue_month,
  mr.recurring_revenue,
  mr.usage_revenue,
  mr.onetime_revenue,
  mr.total_revenue,
  mr.total_discount,
  mr.total_revenue - mr.total_discount AS net_revenue,
  COALESCE(us.total_data_mb, 0) AS data_usage_mb,
  COALESCE(us.total_voice_min, 0) AS voice_usage_min,
  COALESCE(us.total_sms, 0) AS sms_count,
  -- Per-unit economics
  SAFE_DIVIDE(mr.usage_revenue, NULLIF(us.total_data_mb, 0)) AS revenue_per_mb,
  SAFE_DIVIDE(mr.usage_revenue, NULLIF(us.total_voice_min, 0)) AS revenue_per_minute,
  -- ARPU percentile (computed via window)
  PERCENT_RANK() OVER (PARTITION BY mr.revenue_month ORDER BY mr.total_revenue) AS arpu_percentile,
  -- Month-over-month trend
  LAG(mr.total_revenue) OVER (PARTITION BY mr.subscriber_id ORDER BY mr.revenue_month) AS prev_month_revenue,
  SAFE_DIVIDE(
    mr.total_revenue - LAG(mr.total_revenue) OVER (PARTITION BY mr.subscriber_id ORDER BY mr.revenue_month),
    NULLIF(LAG(mr.total_revenue) OVER (PARTITION BY mr.subscriber_id ORDER BY mr.revenue_month), 0)
  ) * 100 AS mom_growth_pct,
  CURRENT_TIMESTAMP() AS computation_timestamp
FROM monthly_revenue mr
LEFT JOIN usage_split us ON mr.subscriber_id = us.subscriber_id AND mr.revenue_month = us.usage_month;

-- ARPU by segment summary
CREATE OR REPLACE VIEW `telco-analytics.analytics_ds.arpu_segment_summary` AS
SELECT
  revenue_month,
  subscriber_segment,
  subscriber_type,
  COUNT(DISTINCT subscriber_id) AS subscriber_count,
  AVG(total_revenue) AS avg_arpu,
  APPROX_QUANTILES(total_revenue, 4)[OFFSET(2)] AS median_arpu,
  MIN(total_revenue) AS min_arpu,
  MAX(total_revenue) AS max_arpu,
  SUM(total_revenue) AS total_segment_revenue,
  AVG(data_usage_mb) AS avg_data_usage_mb,
  AVG(voice_usage_min) AS avg_voice_min
FROM `telco-analytics.analytics_ds.arpu_monthly`
GROUP BY revenue_month, subscriber_segment, subscriber_type;
--- network_quality ---
-- =============================================================================
-- Network Quality Scoring & Analysis
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.network_quality_scores` AS
WITH site_metrics AS (
  SELECT
    k.site_id,
    cs.site_name,
    cs.technology,
    k.kpi_date,
    AVG(CASE WHEN k.kpi_name = 'call_setup_success_rate' THEN k.kpi_value END) AS cssr,
    AVG(CASE WHEN k.kpi_name = 'call_drop_rate' THEN k.kpi_value END) AS cdr_rate,
    AVG(CASE WHEN k.kpi_name = 'handover_success_rate' THEN k.kpi_value END) AS hosr,
    AVG(CASE WHEN k.kpi_name = 'dl_throughput_mbps' THEN k.kpi_value END) AS avg_dl_throughput,
    AVG(CASE WHEN k.kpi_name = 'ul_throughput_mbps' THEN k.kpi_value END) AS avg_ul_throughput,
    AVG(CASE WHEN k.kpi_name = 'latency_ms' THEN k.kpi_value END) AS avg_latency,
    AVG(CASE WHEN k.kpi_name = 'packet_loss_pct' THEN k.kpi_value END) AS avg_packet_loss,
    MAX(k.subscriber_count) AS peak_subscribers,
    MAX(k.traffic_volume_gb) AS peak_traffic_gb
  FROM `telco-analytics.network_inventory_ds.network_kpi` k
  JOIN `telco-analytics.network_inventory_ds.cell_site` cs ON k.site_id = cs.site_id
  WHERE k.kpi_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
  GROUP BY k.site_id, cs.site_name, cs.technology, k.kpi_date
)
SELECT
  site_id,
  site_name,
  technology,
  kpi_date,
  cssr,
  cdr_rate,
  hosr,
  avg_dl_throughput,
  avg_ul_throughput,
  avg_latency,
  avg_packet_loss,
  peak_subscribers,
  peak_traffic_gb,
  -- Composite network quality score (0-100)
  ROUND(
    COALESCE(cssr, 95) * 0.20 +
    (100 - COALESCE(cdr_rate, 2) * 10) * 0.20 +
    COALESCE(hosr, 95) * 0.15 +
    LEAST(COALESCE(avg_dl_throughput, 10) / 100 * 100, 100) * 0.20 +
    (100 - LEAST(COALESCE(avg_latency, 30), 100)) * 0.15 +
    (100 - COALESCE(avg_packet_loss, 1) * 20) * 0.10
  , 2) AS quality_score,
  CURRENT_TIMESTAMP() AS computation_timestamp
FROM site_metrics;
--- five_g_monetization ---
-- =============================================================================
-- 5G Monetization Analytics
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

-- Network Slice Revenue Analysis
CREATE OR REPLACE TABLE `telco-analytics.analytics_ds.slice_revenue_analysis` AS
SELECT
  nsu.slice_id,
  nsu.slice_name,
  nsu.slice_type,
  DATE_TRUNC(nsu.usage_date, MONTH) AS revenue_month,
  COUNT(DISTINCT nsu.subscriber_id) AS active_subscribers,
  SUM(nsu.bytes_uplink + nsu.bytes_downlink) / (1024*1024*1024) AS total_traffic_gb,
  SUM(nsu.rated_amount) AS total_revenue,
  AVG(nsu.rated_amount) AS arpu_per_subscriber,
  AVG(nsu.average_latency_ms) AS avg_latency_ms,
  AVG(nsu.throughput_actual_mbps) AS avg_throughput_mbps,
  COUNTIF(nsu.sla_met_flag = FALSE) AS sla_breaches,
  SAFE_DIVIDE(COUNTIF(nsu.sla_met_flag), COUNT(*)) * 100 AS sla_compliance_pct,
  -- Revenue per GB
  SAFE_DIVIDE(SUM(nsu.rated_amount), SUM(nsu.bytes_uplink + nsu.bytes_downlink) / (1024*1024*1024)) AS revenue_per_gb,
  CURRENT_TIMESTAMP() AS computation_timestamp
FROM `telco-analytics.usage_analytics_ds.network_slice_usage` nsu
WHERE nsu.usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH)
GROUP BY nsu.slice_id, nsu.slice_name, nsu.slice_type, revenue_month;

-- 4G vs 5G Migration & ARPU Cannibalization
CREATE OR REPLACE VIEW `telco-analytics.analytics_ds.migration_impact` AS
SELECT
  sp.subscriber_segment,
  sd.is_5g_capable,
  COUNT(DISTINCT sp.subscriber_id) AS subscriber_count,
  AVG(us.total_charge) AS avg_daily_revenue,
  AVG(us.data_usage_mb) AS avg_daily_data_mb,
  AVG(us.data_usage_5g_mb) AS avg_daily_5g_data_mb,
  AVG(us.data_usage_4g_mb) AS avg_daily_4g_data_mb,
  -- Revenue efficiency: revenue per MB
  SAFE_DIVIDE(SUM(us.total_charge), SUM(us.data_usage_mb)) AS revenue_per_mb,
  SAFE_DIVIDE(SUM(us.total_charge), SUM(us.data_usage_5g_mb)) AS revenue_per_5g_mb,
  SAFE_DIVIDE(SUM(us.total_charge), SUM(us.data_usage_4g_mb)) AS revenue_per_4g_mb
FROM `telco-analytics.subscriber_ds.subscriber_profile` sp
LEFT JOIN `telco-analytics.subscriber_ds.subscriber_device` sd
  ON sp.subscriber_id = sd.subscriber_id AND sd.device_status = 'active'
LEFT JOIN `telco-analytics.usage_analytics_ds.usage_summary` us
  ON sp.subscriber_id = us.subscriber_id
  AND us.usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
  AND us.usage_period = 'daily'
WHERE sp.status = 'active'
GROUP BY sp.subscriber_segment, sd.is_5g_capable;

-- Edge Compute Revenue
CREATE OR REPLACE VIEW `telco-analytics.analytics_ds.edge_compute_revenue` AS
SELECT
  ecs.application_name,
  ecs.edge_location,
  DATE_TRUNC(ecs.usage_date, MONTH) AS revenue_month,
  COUNT(DISTINCT ecs.subscriber_id) AS active_users,
  COUNT(*) AS session_count,
  SUM(ecs.duration_seconds) / 3600 AS total_hours,
  SUM(ecs.data_processed_mb) / 1024 AS total_data_gb,
  SUM(ecs.compute_units) AS total_compute_units,
  SUM(ecs.rated_amount) AS total_revenue,
  AVG(ecs.latency_ms) AS avg_latency_ms
FROM `telco-analytics.usage_analytics_ds.edge_compute_session` ecs
WHERE ecs.usage_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH)
GROUP BY ecs.application_name, ecs.edge_location, revenue_month;
