-- =============================================================================
-- Amazon Redshift DDL for subscriber_ds
-- Domain: subscriber
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

CREATE TABLE IF NOT EXISTS subscriber_ds.subscriber_profile
(
  subscriber_id VARCHAR(4096) NOT NULL,
  msisdn VARCHAR(4096),
  status VARCHAR(4096),
  activation_date DATE
)
;

