-- =============================================================================
-- Azure Synapse Analytics DDL for subscriber_ds
-- Domain: subscriber
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

CREATE TABLE [subscriber_ds].[subscriber_profile]
(
  [subscriber_id] NVARCHAR(4000) NOT NULL,
  [msisdn] NVARCHAR(4000),
  [status] NVARCHAR(4000),
  [activation_date] DATE
)
WITH
(
  DISTRIBUTION = ROUND_ROBIN
);

