-- =============================================================================
-- BigQuery DDL for subscriber_ds
-- Domain: subscriber
-- Generated by TAA (Telco Analytics Accelerator)
-- =============================================================================

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_profile`
(
  subscriber_id STRING NOT NULL OPTIONS(description="Unique subscriber identifier (primary key)"),
  account_id STRING NOT NULL OPTIONS(description="Parent billing/service account identifier (FK to account)"),
  msisdn STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/msisdn"]) OPTIONS(description="Mobile Subscriber ISDN Number (E.164 format)"),
  imsi STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/imsi"]) OPTIONS(description="International Mobile Subscriber Identity"),
  sim_serial STRING NOT NULL OPTIONS(description="SIM card serial number (ICCID, up to 20 digits)"),
  first_name STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/name"]) OPTIONS(description="Subscriber given / first name"),
  last_name STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/name"]) OPTIONS(description="Subscriber family / last name"),
  email STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/email"]) OPTIONS(description="Primary contact email address"),
  phone_secondary STRING OPTIONS(description="Secondary / alternative contact phone number"),
  national_id STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/national_id"]) OPTIONS(description="Government-issued national identification number"),
  date_of_birth DATE OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/date_of_birth"]) OPTIONS(description="Subscriber date of birth"),
  gender STRING OPTIONS(description="Gender (male/female/non_binary/undisclosed)"),
  nationality STRING OPTIONS(description="ISO 3166-1 alpha-2 nationality code"),
  city STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="City of primary residence"),
  state STRING OPTIONS(description="State or province of primary residence"),
  country STRING OPTIONS(description="ISO 3166-1 alpha-2 country code"),
  postal_code STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Postal / ZIP code of primary residence"),
  geo_latitude FLOAT64 OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/location"]) OPTIONS(description="Latitude of primary residence (WGS 84)"),
  geo_longitude FLOAT64 OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/location"]) OPTIONS(description="Longitude of primary residence (WGS 84)"),
  subscriber_type STRING NOT NULL OPTIONS(description="Billing relationship type (postpaid/prepaid/hybrid)"),
  subscriber_segment STRING OPTIONS(description="High-level commercial segment (mass/gold/platinum/vip)"),
  lifecycle_stage STRING NOT NULL OPTIONS(description="Customer lifecycle stage (prospect/active/dormant/churned)"),
  credit_limit NUMERIC OPTIONS(description="Approved credit limit in local currency"),
  credit_score FLOAT64 OPTIONS(description="Internal or bureau credit score (0-1000 scale)"),
  preferred_channel STRING OPTIONS(description="Preferred contact channel (sms/email/push/call/whatsapp)"),
  language_preference STRING OPTIONS(description="Preferred language (ISO 639-1 code)"),
  kyc_status STRING OPTIONS(description="Know-Your-Customer verification status (pending/verified/rejected/expired)"),
  kyc_date DATE OPTIONS(description="Date KYC verification was last completed or refreshed"),
  sim_type STRING OPTIONS(description="SIM form factor (physical/eSIM/iSIM)"),
  network_type STRING OPTIONS(description="Highest registered network technology (2G/3G/4G/5G)"),
  handset_model STRING OPTIONS(description="Current primary handset model name"),
  os_type STRING OPTIONS(description="Operating system of primary device (android/ios/other)"),
  activation_date DATE NOT NULL OPTIONS(description="Date the subscriber line was first activated"),
  last_activity_date DATE OPTIONS(description="Date of most recent network or billing activity"),
  churn_risk_score FLOAT64 OPTIONS(description="Predictive churn probability (0.0 - 1.0)"),
  lifetime_value NUMERIC OPTIONS(description="Estimated customer lifetime value in local currency"),
  referral_code STRING OPTIONS(description="Referral or promo code used at acquisition"),
  dealer_code STRING OPTIONS(description="Acquiring dealer / point-of-sale code"),
  credit_class STRING OPTIONS(description="Credit classification tier (A/B/C/D/E)"),
  status STRING NOT NULL OPTIONS(description="Subscriber line status (active/suspended/barred/terminated)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)"),
  updated_at TIMESTAMP OPTIONS(description="Record last-update timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_profile table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.account`
(
  account_id STRING NOT NULL OPTIONS(description="Unique account identifier (primary key)"),
  account_name STRING NOT NULL OPTIONS(description="Human-readable account name or label"),
  account_type STRING NOT NULL OPTIONS(description="Account classification (individual/corporate/dealer)"),
  billing_type STRING NOT NULL OPTIONS(description="Billing model (postpaid/prepaid/hybrid)"),
  parent_account_id STRING OPTIONS(description="Parent account for hierarchical structures (self-ref FK)"),
  payment_method STRING OPTIONS(description="Default payment method (credit_card/bank_transfer/direct_debit/mobile_money/cash)"),
  payment_term_days INT64 OPTIONS(description="Net payment terms in days (e.g. 30)"),
  credit_class STRING OPTIONS(description="Credit classification tier (A/B/C/D/E)"),
  credit_limit NUMERIC OPTIONS(description="Total credit limit for the account in local currency"),
  currency STRING NOT NULL OPTIONS(description="ISO 4217 currency code (e.g. USD, EUR, KES)"),
  tax_exemption_flag BOOL OPTIONS(description="Whether the account is exempt from tax"),
  tax_id STRING OPTIONS(description="Tax identification number (VAT/TIN/GST)"),
  bill_cycle_day INT64 OPTIONS(description="Day of month the billing cycle closes (1-28)"),
  bill_format STRING OPTIONS(description="Preferred bill delivery format (paper/email/sms/portal)"),
  bill_language STRING OPTIONS(description="Language for bill rendering (ISO 639-1 code)"),
  dunning_level INT64 OPTIONS(description="Current dunning escalation level (0 = none)"),
  collection_status STRING OPTIONS(description="Collections status (current/overdue/in_collections/written_off)"),
  outstanding_balance NUMERIC OPTIONS(description="Total outstanding balance on the account"),
  last_payment_date DATE OPTIONS(description="Date of the most recent payment received"),
  last_payment_amount NUMERIC OPTIONS(description="Amount of the most recent payment received"),
  account_status STRING NOT NULL OPTIONS(description="Account lifecycle status (active/suspended/closed)"),
  responsible_party_id STRING OPTIONS(description="Party (individual/org) legally responsible for the account"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)"),
  updated_at TIMESTAMP OPTIONS(description="Record last-update timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="account table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.account_hierarchy`
(
  hierarchy_id STRING NOT NULL OPTIONS(description="Unique hierarchy link identifier (primary key)"),
  parent_account_id STRING NOT NULL OPTIONS(description="Account ID of the parent node (FK to account)"),
  child_account_id STRING NOT NULL OPTIONS(description="Account ID of the child node (FK to account)"),
  hierarchy_level INT64 NOT NULL OPTIONS(description="Depth level in the hierarchy tree (root = 0)"),
  relationship_type STRING NOT NULL OPTIONS(description="Nature of the link (parent/child/sponsor/reseller)"),
  cost_center STRING OPTIONS(description="Cost-centre or department code for allocation"),
  spending_limit NUMERIC OPTIONS(description="Maximum spend allowed for the child under this link"),
  spending_limit_currency STRING OPTIONS(description="ISO 4217 currency code for the spending limit"),
  effective_date DATE NOT NULL OPTIONS(description="Date this hierarchy link becomes effective"),
  expiry_date DATE OPTIONS(description="Date this hierarchy link expires (null = indefinite)"),
  status STRING NOT NULL OPTIONS(description="Link status (active/inactive/pending)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="account_hierarchy table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_address`
(
  address_id STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Unique address record identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Owning subscriber identifier (FK to subscriber_profile)"),
  address_type STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Address purpose (home/work/billing/installation/shipping)"),
  address_line_1 STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Primary street address line"),
  address_line_2 STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Secondary address line (apt, suite, floor, etc.)"),
  address_line_3 STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Tertiary address line (building name, landmark)"),
  city STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="City or locality name"),
  state_province STRING OPTIONS(description="State, province, or region"),
  postal_code STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/address"]) OPTIONS(description="Postal or ZIP code"),
  country_code STRING NOT NULL OPTIONS(description="ISO 3166-1 alpha-2 country code"),
  geo_latitude FLOAT64 OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/location"]) OPTIONS(description="Geocoded latitude (WGS 84)"),
  geo_longitude FLOAT64 OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/location"]) OPTIONS(description="Geocoded longitude (WGS 84)"),
  validated_flag BOOL OPTIONS(description="Whether the address has been validated against a postal database"),
  validation_date DATE OPTIONS(description="Date the address was last validated"),
  validation_source STRING OPTIONS(description="Source system used for address validation"),
  primary_flag BOOL NOT NULL OPTIONS(description="Whether this is the subscriber's primary address"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)"),
  updated_at TIMESTAMP OPTIONS(description="Record last-update timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_address table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_consent`
(
  consent_id STRING NOT NULL OPTIONS(description="Unique consent record identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Subscriber granting consent (FK to subscriber_profile)"),
  consent_type STRING NOT NULL OPTIONS(description="Purpose category (marketing/data_processing/third_party/profiling/location/analytics)"),
  channel STRING NOT NULL OPTIONS(description="Communication channel for consent (sms/email/push/call/whatsapp/all)"),
  consent_status STRING NOT NULL OPTIONS(description="Current status (granted/revoked/expired/pending)"),
  consent_date TIMESTAMP NOT NULL OPTIONS(description="Timestamp when consent was granted"),
  revocation_date TIMESTAMP OPTIONS(description="Timestamp when consent was revoked (null if active)"),
  expiry_date DATE OPTIONS(description="Date consent automatically expires if not renewed"),
  legal_basis STRING NOT NULL OPTIONS(description="Legal ground (consent/legitimate_interest/contract/legal_obligation/vital_interest/public_task)"),
  data_controller STRING OPTIONS(description="Name or ID of the data controller entity"),
  data_processor STRING OPTIONS(description="Name or ID of the third-party data processor, if any"),
  jurisdiction STRING OPTIONS(description="Regulatory jurisdiction code (e.g. EU, KE, ZA, SG)"),
  policy_version STRING OPTIONS(description="Version of the privacy policy under which consent was obtained"),
  source STRING OPTIONS(description="Collection source (app/web/call_center/retail/sms)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_consent table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_device`
(
  device_id STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/imei"]) OPTIONS(description="Unique device record identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Subscriber using the device (FK to subscriber_profile)"),
  imei STRING NOT NULL OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/imei"]) OPTIONS(description="International Mobile Equipment Identity (15 digits)"),
  imei_sv STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/imei"]) OPTIONS(description="IMEI Software Version (16 digits)"),
  tac_code STRING OPTIONS(description="Type Allocation Code (first 8 digits of IMEI)"),
  device_make STRING OPTIONS(description="Device manufacturer (e.g. Samsung, Apple, Huawei)"),
  device_model STRING OPTIONS(description="Device model name or number"),
  device_type STRING NOT NULL OPTIONS(description="Device category (handset/tablet/router/wearable/iot/modem)"),
  os_name STRING OPTIONS(description="Operating system name (android/ios/harmonyos/linux/other)"),
  os_version STRING OPTIONS(description="Operating system version string"),
  is_5g_capable BOOL OPTIONS(description="Whether the device supports 5G NR"),
  is_volte_capable BOOL OPTIONS(description="Whether the device supports VoLTE"),
  is_esim_capable BOOL OPTIONS(description="Whether the device supports eSIM provisioning"),
  device_status STRING NOT NULL OPTIONS(description="Current device status (active/lost/stolen/returned/decommissioned)"),
  activation_date DATE NOT NULL OPTIONS(description="Date the device was first activated on the network"),
  deactivation_date DATE OPTIONS(description="Date the device was deactivated or removed"),
  sim_slot INT64 OPTIONS(description="SIM slot number the subscriber line occupies (1/2)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_device table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_balance`
(
  balance_id STRING NOT NULL OPTIONS(description="Unique balance bucket identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Owning subscriber (FK to subscriber_profile)"),
  account_id STRING NOT NULL OPTIONS(description="Associated billing account (FK to account)"),
  balance_type STRING NOT NULL OPTIONS(description="Bucket type (monetary/data/voice/sms/bonus/loyalty_points)"),
  balance_name STRING OPTIONS(description="Human-readable bucket name (e.g. Main Balance, Night Data)"),
  current_value NUMERIC NOT NULL OPTIONS(description="Current remaining value in the bucket"),
  initial_value NUMERIC NOT NULL OPTIONS(description="Original credited value when the bucket was provisioned"),
  reserved_value NUMERIC OPTIONS(description="Value currently reserved/held for in-progress sessions"),
  unit STRING NOT NULL OPTIONS(description="Unit of measure (currency/MB/GB/minutes/seconds/count/points)"),
  effective_date TIMESTAMP NOT NULL OPTIONS(description="Timestamp from which the bucket is usable"),
  expiry_date TIMESTAMP OPTIONS(description="Timestamp at which the bucket expires"),
  auto_renew BOOL OPTIONS(description="Whether the bucket auto-renews on expiry"),
  priority INT64 OPTIONS(description="Depletion priority (lower number consumed first)"),
  last_updated TIMESTAMP NOT NULL OPTIONS(description="Timestamp of last balance mutation")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_balance table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_contract`
(
  contract_id STRING NOT NULL OPTIONS(description="Unique contract identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Subscriber bound by the contract (FK to subscriber_profile)"),
  account_id STRING NOT NULL OPTIONS(description="Billing account for the contract (FK to account)"),
  plan_id STRING OPTIONS(description="Commercial plan / product offering identifier"),
  bundle_id STRING OPTIONS(description="Convergent bundle identifier (if part of a bundle)"),
  contract_type STRING NOT NULL OPTIONS(description="Nature of the contract (new/renewal/upgrade/migration/win_back)"),
  start_date DATE NOT NULL OPTIONS(description="Contract effective start date"),
  end_date DATE OPTIONS(description="Contract scheduled end date"),
  commitment_months INT64 OPTIONS(description="Minimum commitment period in months"),
  monthly_fee NUMERIC OPTIONS(description="Monthly recurring charge in local currency"),
  discount_pct FLOAT64 OPTIONS(description="Percentage discount applied to standard rate (0-100)"),
  early_termination_fee NUMERIC OPTIONS(description="Penalty fee for early contract termination"),
  auto_renew_flag BOOL OPTIONS(description="Whether the contract auto-renews at expiry"),
  device_installment_plan_id STRING OPTIONS(policy_tags=["projects/telco/locations/global/taxonomies/pii/policyTags/imei"]) OPTIONS(description="Reference to device instalment / financing plan"),
  remaining_installments INT64 OPTIONS(description="Number of remaining device instalment payments"),
  channel STRING OPTIONS(description="Sales channel through which the contract was signed (retail/online/call_center/dealer)"),
  status STRING NOT NULL OPTIONS(description="Contract status (draft/active/expired/terminated/cancelled)"),
  activation_date DATE NOT NULL OPTIONS(description="Date the contract was activated / services provisioned"),
  termination_date DATE OPTIONS(description="Date the contract was actually terminated (if applicable)"),
  termination_reason STRING OPTIONS(description="Reason for termination (voluntary/involuntary/ported_out/fraud)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)"),
  updated_at TIMESTAMP OPTIONS(description="Record last-update timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_contract table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_segment`
(
  segment_id STRING NOT NULL OPTIONS(description="Unique segment assignment identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Subscriber being segmented (FK to subscriber_profile)"),
  segment_type STRING NOT NULL OPTIONS(description="Segmentation axis (value/lifecycle/behavioral/demographic/geographic/psychographic)"),
  segment_name STRING NOT NULL OPTIONS(description="Human-readable segment label (e.g. High Value Roamer)"),
  segment_code STRING OPTIONS(description="Machine-readable segment code"),
  segment_value STRING OPTIONS(description="Assigned segment value or tier"),
  score FLOAT64 OPTIONS(description="Numeric score supporting the segment assignment (0-1000)"),
  percentile_rank FLOAT64 OPTIONS(description="Percentile rank within the segment population (0-100)"),
  computation_date DATE NOT NULL OPTIONS(description="Date the segmentation model was last executed"),
  model_version STRING OPTIONS(description="Version identifier of the segmentation model"),
  model_name STRING OPTIONS(description="Name of the segmentation model or pipeline"),
  valid_from DATE NOT NULL OPTIONS(description="Start of the validity window for this assignment"),
  valid_to DATE OPTIONS(description="End of the validity window (null = until next refresh)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_segment table for subscriber domain"
);

CREATE TABLE IF NOT EXISTS `telco-analytics.subscriber_ds.subscriber_notification_preference`
(
  preference_id STRING NOT NULL OPTIONS(description="Unique preference record identifier (primary key)"),
  subscriber_id STRING NOT NULL OPTIONS(description="Subscriber owning the preference (FK to subscriber_profile)"),
  notification_type STRING NOT NULL OPTIONS(description="Notification category (billing/usage_alert/promotion/service/outage/fraud_alert/roaming)"),
  channel STRING NOT NULL OPTIONS(description="Delivery channel (sms/email/push/whatsapp/ivr)"),
  enabled BOOL NOT NULL OPTIONS(description="Whether this notification is currently enabled"),
  threshold_value FLOAT64 OPTIONS(description="Trigger threshold value (e.g. 80 for 80 % usage)"),
  threshold_unit STRING OPTIONS(description="Unit of the threshold (percent/MB/currency/minutes)"),
  frequency STRING OPTIONS(description="Maximum send frequency (realtime/daily/weekly/monthly)"),
  language STRING OPTIONS(description="Preferred language for notifications (ISO 639-1 code)"),
  quiet_hours_start STRING OPTIONS(description="Start of quiet / do-not-disturb window (HH:MM, local time)"),
  quiet_hours_end STRING OPTIONS(description="End of quiet / do-not-disturb window (HH:MM, local time)"),
  timezone STRING OPTIONS(description="IANA timezone for quiet-hours evaluation (e.g. Africa/Nairobi)"),
  created_at TIMESTAMP NOT NULL OPTIONS(description="Record creation timestamp (UTC)"),
  updated_at TIMESTAMP OPTIONS(description="Record last-update timestamp (UTC)")
)
PARTITION BY DATE_TRUNC(activation_date, DAY)
CLUSTER BY subscriber_id
OPTIONS(
  description="subscriber_notification_preference table for subscriber domain"
);

