"""ZIP archive builder for export artefacts."""

from __future__ import annotations

import io
import os
import zipfile
from pathlib import Path
from typing import Any

from taa.infrastructure.export.manifest import ManifestGenerator


class ZipBuilder:
    """Builds ZIP archives from a directory of generated artefacts.

    Walks the output directory, adds every file to a compressed ZIP,
    and optionally injects a ``manifest.json`` with generation metadata.
    """

    def __init__(self) -> None:
        self._manifest_gen = ManifestGenerator()

    def build_from_directory(
        self,
        source_dir: Path,
        *,
        domains: list[str] | None = None,
        jurisdiction: str = "SA",
        vendor: str | None = None,
        include_terraform: bool = True,
        include_pipelines: bool = True,
        include_dags: bool = True,
        include_compliance: bool = True,
    ) -> tuple[bytes, list[dict[str, Any]]]:
        """Package all files under *source_dir* into a ZIP archive.

        Args:
            source_dir: Root directory whose contents will be zipped.
            domains: Domain names for manifest metadata.
            jurisdiction: Jurisdiction code for manifest metadata.
            vendor: Optional BSS vendor for manifest metadata.
            include_terraform: Flag passed to the manifest.
            include_pipelines: Flag passed to the manifest.
            include_dags: Flag passed to the manifest.
            include_compliance: Flag passed to the manifest.

        Returns:
            A tuple of ``(zip_bytes, file_infos)`` where *file_infos* is a
            list of dicts with keys ``path``, ``size``, and ``type``.
        """
        buf = io.BytesIO()
        file_infos: list[dict[str, Any]] = []
        table_names: list[str] = []

        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for root, _dirs, files in os.walk(source_dir):
                for fname in sorted(files):
                    full_path = os.path.join(root, fname)
                    arc_name = os.path.relpath(full_path, source_dir)
                    file_size = os.path.getsize(full_path)
                    zf.write(full_path, arc_name)

                    ext = os.path.splitext(fname)[1].lstrip(".")
                    file_infos.append({
                        "path": arc_name,
                        "size": file_size,
                        "type": ext or "unknown",
                    })

                    # Collect table names from BigQuery DDL files for the
                    # manifest (one .sql per domain).
                    if arc_name.startswith("bigquery/") and ext == "sql":
                        table_names.append(os.path.splitext(fname)[0])

            # Generate and embed manifest.json
            manifest_json = self._manifest_gen.generate(
                domains=domains or [],
                tables=table_names,
                jurisdiction=jurisdiction,
                vendor=vendor,
                file_entries=file_infos,
                include_terraform=include_terraform,
                include_pipelines=include_pipelines,
                include_dags=include_dags,
                include_compliance=include_compliance,
            )
            zf.writestr("manifest.json", manifest_json)
            file_infos.append({
                "path": "manifest.json",
                "size": len(manifest_json.encode("utf-8")),
                "type": "json",
            })

            # Generate and embed a README.md with generation metadata
            readme_content = self._build_readme(
                domains=domains or [],
                jurisdiction=jurisdiction,
                vendor=vendor,
                file_count=len(file_infos),
                include_terraform=include_terraform,
                include_pipelines=include_pipelines,
                include_dags=include_dags,
                include_compliance=include_compliance,
            )
            zf.writestr("README.md", readme_content)
            file_infos.append({
                "path": "README.md",
                "size": len(readme_content.encode("utf-8")),
                "type": "md",
            })

        return buf.getvalue(), file_infos

    @staticmethod
    def _build_readme(
        *,
        domains: list[str],
        jurisdiction: str,
        vendor: str | None,
        file_count: int,
        include_terraform: bool,
        include_pipelines: bool,
        include_dags: bool,
        include_compliance: bool,
    ) -> str:
        """Build a README.md summarising the export contents."""
        lines = [
            "# TAA Export Pack",
            "",
            "Generated by **TAA - Telco Analytics Accelerator**.",
            "",
            "## Parameters",
            "",
            f"- **Domains**: {', '.join(domains) if domains else 'all'}",
            f"- **Jurisdiction**: {jurisdiction}",
            f"- **Vendor**: {vendor or 'none'}",
            "",
            "## Contents",
            "",
            "| Directory | Description |",
            "|-----------|-------------|",
            "| `bigquery/` | BigQuery DDL files (.sql) |",
        ]
        if include_dags:
            lines.append("| `airflow/` | Airflow DAG definitions (.py) |")
        if include_pipelines:
            lines.append("| `dataflow/` | Dataflow pipeline code (.py) |")
        if include_terraform:
            lines.append("| `terraform/` | Terraform IaC configs (.tf) |")
        if include_compliance:
            lines.append("| `compliance/` | Compliance reports (.json, .md) |")
        lines.extend([
            "",
            f"**Total files**: {file_count}",
            "",
            "## Usage",
            "",
            "```bash",
            "# Apply BigQuery DDL",
            "bq query --use_legacy_sql=false < bigquery/<domain>.sql",
            "",
            "# Deploy Terraform",
            "cd terraform && terraform init && terraform plan",
            "```",
        ])
        return "\n".join(lines) + "\n"
